### ISSUE TITLE
Next.js documentation don't load

### ISSUE THREAD

**Issue by Exatoon27** [sunxen/docsfinder#1]
**When I am trying to open the documentation of Next.js I get the following screen:**
### Tab in VS Code
<img src="https://github.com/sunxen/docsfinder/assets/73707496/047bea34-12e0-4f40-b832-9de8b830528e" width="600" height="360">

<em>The screen says: Application error: a client-side exception has occurred (see the browser console for more information).</em>
### Browser console
When I enter to the console I see the next error:
<img src="https://github.com/sunxen/docsfinder/assets/73707496/dd99d01a-75f7-4925-8652-d815060185a7" width="600" height="360">
<em>It seems to be a error about cors</em>

**I don't know if I need to make a extra config, but without making changes and directly using the extension I get that screen.**

**Comment by sunxen** [comment]
fix: Next.js docs not support iframe anymore
